# Generated by Django 3.1.2 on 2020-11-22 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('ca', 'CA'), ('intca', 'INTCA'), ('server', 'SERVER'), ('client', 'CLIENT')], max_length=10)),
                ('subject', models.CharField(max_length=25)),
                ('path', models.CharField(max_length=25)),
            ],
        ),
    ]
