# Generated by Django 3.1.2 on 2020-10-17 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LogEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('UP', 'up'), ('DOWN', 'down'), ('IPCHANGE', 'ipchange'), ('ROUTE_UP', 'route-up'), ('TLS_VERIFY', 'tls-verify'), ('AUTH_USER_PASS_VERIFY', 'auth-user-pass-verify'), ('CLIENT_CONNECT', 'client-connect'), ('CLIENT_DISCONNECT', 'client-disconnect'), ('LEARN_ADDRESS', 'learn-address')], max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='LogEntryAttr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('value', models.CharField(max_length=100)),
                ('logentry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='log.logentry')),
            ],
        ),
    ]
